Hw8
vuan484/Homework pull request #3
Opened 2022-06-05 11:30 UTC by vuan484

2022-06-08 12:57 UTC, dmitrii-kruglov requested changes
нужно доделать

2022-06-08 12:57 UTC, dmitrii-kruglov commented on HW8
> +result = first / second;
сделайте, пожалуйста, собственное исключение

2022-06-08 12:57 UTC, dmitrii-kruglov commented on HW8-1.cpp
> +        result = request(login);
эта переменная не нужна, сделайте, пожалуйста, без неё.

2022-06-08 13:49 UTC, vuan484 commented on HW8-1.cpp
> +        result = request(login);
я сделал

2022-06-08 21:31 UTC, dmitrii-kruglov commented on HW8-1.cpp
> +        result = request(login);
Теперь вторая работает не правильно, а по первой не вижу изменений.

2022-06-08 21:32 UTC, dmitrii-kruglov requested changes
нужно в первой доделать, а во второй сделать так, чтобы работало корректно

2022-06-09 11:55 UTC, vuan484 commented on HW8-1.cpp
> +        result = request(login);
первую редактировал

2022-06-15 15:58 UTC, dmitrii-kruglov approved these changes
Зачтено, но балл снижен.

2022-06-24 14:08 UTC, merged